# Generated by Django 2.2.6 on 2019-10-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, max_length=45, null=True)),
                ('loser', models.CharField(blank=True, max_length=45, null=True)),
                ('guest', models.CharField(blank=True, max_length=45, null=True)),
                ('host', models.CharField(blank=True, max_length=45, null=True)),
                ('date_match', models.CharField(blank=True, max_length=45, null=True)),
                ('score_guest', models.CharField(blank=True, max_length=45, null=True)),
                ('score_host', models.CharField(blank=True, max_length=45, null=True)),
                ('final_score', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
