# Generated by Django 2.2.6 on 2019-10-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20191028_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_accident', models.DateField(blank=True, null=True)),
                ('break_time', models.IntegerField(blank=True, null=True)),
                ('type_of_injury', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('amount_of_wins', models.IntegerField(blank=True, null=True)),
                ('amount_of_losses', models.IntegerField(blank=True, null=True)),
                ('records', models.CharField(blank=True, max_length=45, null=True)),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('games', models.ManyToManyField(related_name='teams', to='league.Game')),
                ('players', models.ManyToManyField(related_name='teams', to='league.Player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_color', models.CharField(blank=True, max_length=45, null=True)),
                ('away_color', models.CharField(blank=True, max_length=45, null=True)),
                ('arena_address', models.CharField(blank=True, max_length=45, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_details', to='league.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(related_name='schedules', to='league.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.CharField(blank=True, max_length=45, null=True)),
                ('is_menager', models.CharField(blank=True, max_length=45, null=True)),
                ('is_player', models.CharField(blank=True, max_length=45, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='league.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, null=True)),
                ('rebounds', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='league.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_licences', to='league.Player')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=45, null=True)),
                ('schedule', models.ManyToManyField(related_name='leagues', to='league.Schedule')),
                ('teams', models.ManyToManyField(related_name='leagues', to='league.Team')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOfInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injuries', models.ManyToManyField(related_name='histories_of_injuries', to='league.Injury')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories_of_injuries', to='league.Player')),
            ],
        ),
    ]
