# Generated by Django 2.2.6 on 2019-11-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_historyofinjury_injury_league_playerlicense_playerstatistic_role_schedule_team_teamdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_menager',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_player',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
