# Generated by Django 2.2.6 on 2019-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20191102_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
