# Generated by Django 2.2.6 on 2019-11-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_auto_20191103_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_match',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='final_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='guest',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_guest',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_host',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
