# Generated by Django 2.2.6 on 2019-11-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20191104_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='is_menager',
            new_name='is_manager',
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='arena_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
