# Generated by Django 2.2.6 on 2019-11-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20191108_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
