# Generated by Django 2.2.6 on 2019-12-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_schedule_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guest',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='game_guest', to='league.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_host', to='league.Team'),
        ),
    ]
