# Generated by Django 2.2.6 on 2019-12-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_auto_20191209_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='license_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PlayerLicense',
        ),
    ]
