# Generated by Django 2.2.6 on 2020-01-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_auto_20191214_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teams',
            field=models.ManyToManyField(related_name='schedules', to='league.Team'),
        ),
    ]
