# Generated by Django 2.2.6 on 2020-01-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_schedule_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='champions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Team'),
        ),
    ]
